package com.kaanf.core.designsystem.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Color.Companion.Transparent

val LocalExtendedColors = staticCompositionLocalOf { LightExtendedColors }

val ColorScheme.extended: ExtendedColors
    @ReadOnlyComposable
    @Composable
    get() = LocalExtendedColors.current

@Immutable
data class ExtendedColors(
    val primaryHover: Color,
    val destructiveHover: Color,
    val destructiveSecondaryOutline: Color,
    val disabledOutline: Color,
    val disabledFill: Color,
    val successOutline: Color,
    val success: Color,
    val onSuccess: Color,
    val secondaryFill: Color,
    val textPrimary: Color,
    val textTertiary: Color,
    val textSecondary: Color,
    val textPlaceholder: Color,
    val textDisabled: Color,
    val surfaceLower: Color,
    val surfaceHigher: Color,
    val surfaceOutline: Color,
    val overlay: Color,
    val accentBlue: Color,
    val accentPurple: Color,
    val accentViolet: Color,
    val accentPink: Color,
    val accentOrange: Color,
    val accentYellow: Color,
    val accentGreen: Color,
    val accentTeal: Color,
    val accentLightBlue: Color,
    val accentGrey: Color,
    val cakeViolet: Color,
    val cakeGreen: Color,
    val cakeBlue: Color,
    val cakePink: Color,
    val cakeOrange: Color,
    val cakeYellow: Color,
    val cakeTeal: Color,
    val cakePurple: Color,
    val cakeRed: Color,
    val cakeMint: Color,
    val iconPrimary: Color,
    val buttonDisabledBg: Color,
    val buttonDefaultBg: Color,
    val buttonFocusedBg: Color,
    val buttonOutline: Color,
    val buttonFocusedOutline: Color,
    val buttonPlaceholderTextColor: Color,
    val buttonFocusedTextColor: Color,
    val buttonDisabledTextColor: Color,
    val primaryTextColor: Color,
    val secondaryTextColor: Color,
)

val LightExtendedColors =
    ExtendedColors(
        primaryHover = Primary400,
        destructiveHover = ChirpRed600,
        destructiveSecondaryOutline = ChirpRed200,
        disabledOutline = ChirpBase200,
        disabledFill = Primary200,
        successOutline = ChirpBrand100,
        success = ChirpBrand600,
        onSuccess = ChirpBase0,
        secondaryFill = ChirpBase100,
        textPrimary = ChirpBase1000,
        textTertiary = ChirpBase800,
        textSecondary = ChirpBase900,
        textPlaceholder = ChirpBase700,
        textDisabled = White,
        surfaceLower = ChirpBase100,
        surfaceHigher = ChirpBase100,
        surfaceOutline = ChirpBase1000Alpha14,
        overlay = ChirpBase1000Alpha80,
        accentBlue = ChirpBlue,
        accentPurple = ChirpPurple,
        accentViolet = ChirpViolet,
        accentPink = ChirpPink,
        accentOrange = ChirpOrange,
        accentYellow = ChirpYellow,
        accentGreen = ChirpGreen,
        accentTeal = ChirpTeal,
        accentLightBlue = ChirpLightBlue,
        accentGrey = ChirpGrey,
        cakeViolet = ChirpCakeLightViolet,
        cakeGreen = ChirpCakeLightGreen,
        cakeBlue = ChirpCakeLightBlue,
        cakePink = ChirpCakeLightPink,
        cakeOrange = ChirpCakeLightOrange,
        cakeYellow = ChirpCakeLightYellow,
        cakeTeal = ChirpCakeLightTeal,
        cakePurple = ChirpCakeLightPurple,
        cakeRed = ChirpCakeLightRed,
        cakeMint = ChirpCakeLightMint,
        iconPrimary = Neutral900,
        buttonOutline = Divider,
        buttonFocusedOutline = Primary400,
        buttonPlaceholderTextColor = Neutral300,
        buttonFocusedTextColor = Neutral900,
        buttonDisabledTextColor = Neutral300,
        buttonDisabledBg = Neutral200,
        buttonDefaultBg = Transparent,
        buttonFocusedBg = Primary50,
        primaryTextColor = Neutral900,
        secondaryTextColor = Neutral300,
    )

val DarkExtendedColors =
    ExtendedColors(
        primaryHover = ChirpBrand600,
        destructiveHover = ChirpRed600,
        destructiveSecondaryOutline = ChirpRed200,
        disabledOutline = ChirpBase900,
        disabledFill = Primary200,
        successOutline = ChirpBrand500Alpha40,
        success = ChirpBrand500,
        onSuccess = ChirpBase1000,
        secondaryFill = ChirpBase900,
        textPrimary = ChirpBase0,
        textTertiary = ChirpBase200,
        textSecondary = ChirpBase150,
        textPlaceholder = ChirpBase400,
        textDisabled = White,
        surfaceLower = ChirpBase1000,
        surfaceHigher = ChirpBase900,
        surfaceOutline = ChirpBase100Alpha10Alt,
        overlay = ChirpBase1000Alpha80,
        accentBlue = ChirpBlue,
        accentPurple = ChirpPurple,
        accentViolet = ChirpViolet,
        accentPink = ChirpPink,
        accentOrange = ChirpOrange,
        accentYellow = ChirpYellow,
        accentGreen = ChirpGreen,
        accentTeal = ChirpTeal,
        accentLightBlue = ChirpLightBlue,
        accentGrey = ChirpGrey,
        iconPrimary = White,
        cakeViolet = ChirpCakeDarkViolet,
        cakeGreen = ChirpCakeDarkGreen,
        cakeBlue = ChirpCakeDarkBlue,
        cakePink = ChirpCakeDarkPink,
        cakeOrange = ChirpCakeDarkOrange,
        cakeYellow = ChirpCakeDarkYellow,
        cakeTeal = ChirpCakeDarkTeal,
        cakePurple = ChirpCakeDarkPurple,
        cakeRed = ChirpCakeDarkRed,
        cakeMint = ChirpCakeDarkMint,
        buttonOutline = Neutral300,
        buttonFocusedOutline = Primary400,
        buttonPlaceholderTextColor = Neutral200,
        buttonFocusedTextColor = White,
        buttonDisabledTextColor = Neutral200,
        buttonDisabledBg = Neutral200,
        buttonDefaultBg = Transparent,
        buttonFocusedBg = Neutral800,
        primaryTextColor = White,
        secondaryTextColor = Neutral200,
    )

val LightColorScheme =
    lightColorScheme(
        primary = Primary400,
        onPrimary = White,
        primaryContainer = ChirpBrand100,
        onPrimaryContainer = ChirpBrand900,
        secondary = ChirpBase700,
        onSecondary = ChirpBase0,
        secondaryContainer = ChirpBase100,
        onSecondaryContainer = ChirpBase900,
        tertiary = ChirpBrand900,
        onTertiary = ChirpBase0,
        tertiaryContainer = ChirpBrand100,
        onTertiaryContainer = ChirpBrand1000,
        error = ChirpRed500,
        onError = ChirpBase0,
        errorContainer = ChirpRed200,
        onErrorContainer = ChirpRed600,
        background = White,
        onBackground = ChirpBase0,
        surface = ChirpBase0,
        onSurface = ChirpBase1000,
        surfaceVariant = ChirpBase100,
        onSurfaceVariant = ChirpBase900,
        outline = Divider,
        outlineVariant = ChirpBase200,
    )

val DarkColorScheme =
    darkColorScheme(
        primary = Primary400,
        onPrimary = White,
        primaryContainer = ChirpBrand900,
        onPrimaryContainer = ChirpBrand500,
        secondary = ChirpBase400,
        onSecondary = ChirpBase1000,
        secondaryContainer = ChirpBase900,
        onSecondaryContainer = ChirpBase150,
        tertiary = ChirpBrand500,
        onTertiary = ChirpBase1000,
        tertiaryContainer = ChirpBrand900,
        onTertiaryContainer = ChirpBrand500,
        error = ChirpRed500,
        onError = ChirpBase0,
        errorContainer = ChirpRed600,
        onErrorContainer = ChirpRed200,
        background = Neutral900,
        onBackground = ChirpBase0,
        surface = ChirpBase950,
        onSurface = ChirpBase0,
        surfaceVariant = ChirpBase900,
        onSurfaceVariant = ChirpBase150,
        outline = Divider,
        outlineVariant = ChirpBase800,
    )
